services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dengue
      MYSQL_DATABASE: dengueDetectDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+aiomysql://youruser:yourpassword@db:3306/mydatabase

  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
  db_data:
